events {}

http {
    upstream cache_cluster {
        server cache-a:8081;
        server cache-b:8082;
        server cache-c:8083;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://cache_cluster;
        }
    }
}